package com.uktech.kladovka.recordplay;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class AddingNewProductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/Users/mac/ITProjects/chromedriver_mac64/chromedriver");

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addingnewproduct() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("email")).sendKeys("test1@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("54321");
    driver.findElement(By.cssSelector(".custom-control-label")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
    driver.findElement(By.linkText("Catalog")).click();
    driver.findElement(By.linkText("Add New Product to Catalog")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("New Product created by Selenium");
    driver.findElement(By.name("category")).click();
    {
      WebElement dropdown = driver.findElement(By.name("category"));
      dropdown.findElement(By.xpath("//option[. = 'Туалетний папір']")).click();
    }
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Test description");
    driver.findElement(By.name("itemPrice")).click();
    driver.findElement(By.name("itemPrice")).sendKeys("187");
    driver.findElement(By.name("store")).click();
    {
      WebElement dropdown = driver.findElement(By.name("store"));
      dropdown.findElement(By.xpath("//option[. = 'Епіцентр']")).click();
    }
    driver.findElement(By.name("link")).click();
    driver.findElement(By.name("link")).sendKeys("https://epicentrk.ua/ua/shop/tualetnaya-bumaga-zewa-deluxe-sashmere-peach-8-sht.html?gclid=CjwKCAjw-IWkBhBTEiwA2exyO4eF0lHNAWMtKC-tzCRyj5NfI2LcX6TagfKsanT6Jb_tNfukyGeO5xoCg5UQAvD_BwE");
    driver.findElement(By.cssSelector("form:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("test1@gmail.com")).click();
    driver.findElement(By.cssSelector(".d-flex > .dropdown-item")).click();
  }
}
